### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by dany-cb** [dany-cb/Clone_SpaceX#5]
### Description
Creating the Menu Bar along with the icon and the hamburger menu using a Mobile-first approach

#### Tasks
- [x] Add component Header under /src/components
- [x] Add component Hamburger to render the hamburger menu inside /src/components with onClick functionalities
- [x] Add responsiveness for larger screens
- [x] Add Animation
