### ISSUE TITLE
Create Sections

### ISSUE THREAD

**Issue by dany-cb** [dany-cb/Clone_SpaceX#6]
#### Description
Creating component to render the inner features section as shown below with Mobile-first approach
<img src="https://user-images.githubusercontent.com/80827217/182560209-108b6652-93d5-45c4-9570-084ac9acec6a.png" width="300px"/>

#### Tasks
- [x] Create component /src/section
- [x] Create an object InnerFeatures with the location of image and the appropriate Title text
- [x] Render all the sections by looping through the InnerFeatures
- [x] Check for responsiveness
- [ ] Add downward arrow and its animation
